blank_issues_enabled: false
contact_links:
  - name: ðŸ“˜ PhantomNet Documentation
    url: https://github.com/saiarjunkoyalkar756-sudo/PhantomNet-v2.0/docs
    about: Refer to project documentation before opening a new issue.
